"""author provided by user

Revision ID: 0992bc1714e3
Revises: 08b2eb475176
Create Date: 2026-04-10 15:33:46.693559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0992bc1714e3'
down_revision: Union[str, Sequence[str], None] = '08b2eb475176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('provided_by_user', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'author', ['id'])
    op.create_foreign_key(None, 'author', 'user', ['provided_by_user'], ['id'])
    op.create_unique_constraint(None, 'genre', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'text', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'text', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'provided_by_user')
    # ### end Alembic commands ###
