"""text may be visible

Revision ID: 5aec4e4dd92c
Revises: 0992bc1714e3
Create Date: 2026-04-10 16:42:56.771917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aec4e4dd92c'
down_revision: Union[str, Sequence[str], None] = '0992bc1714e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'is_visible')
    # ### end Alembic commands ###
