"""on cascade deleting

Revision ID: 717dc5ce01c8
Revises: d3d248102168
Create Date: 2026-06-24 15:05:54.230847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717dc5ce01c8'
down_revision: Union[str, Sequence[str], None] = 'd3d248102168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_provided_by_user_fkey'), 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'user', ['provided_by_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('text_provided_by_user_fkey'), 'text', type_='foreignkey')
    op.drop_constraint(op.f('text_author_id_fkey'), 'text', type_='foreignkey')
    op.drop_constraint(op.f('text_genre_id_fkey'), 'text', type_='foreignkey')
    op.create_foreign_key(None, 'text', 'user', ['provided_by_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'text', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'text', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_role_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_id_fkey'), 'user', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.create_foreign_key(op.f('text_genre_id_fkey'), 'text', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('text_author_id_fkey'), 'text', 'author', ['author_id'], ['id'])
    op.create_foreign_key(op.f('text_provided_by_user_fkey'), 'text', 'user', ['provided_by_user'], ['id'])
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key(op.f('author_provided_by_user_fkey'), 'author', 'user', ['provided_by_user'], ['id'])
    # ### end Alembic commands ###
