upstream api_upstream {
    server web:8080;
}

upstream frontend_upstream {
    server frontend:80;
}

upstream grafana_upstream {
    server grafana:3000;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    server_tokens off;

    client_max_body_size 200M;

    location = /healthz {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location ~ ^/(api|admin|docs|openapi.json|metrics)(/|$) {
        proxy_pass http://api_upstream;
        include /etc/nginx/app/include.forwarded;
        include /etc/nginx/app/include.websocket;
        proxy_redirect off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location /grafana/ {
        proxy_pass http://grafana_upstream;
        include /etc/nginx/app/include.forwarded;
        include /etc/nginx/app/include.websocket;
    }

    location / {
        proxy_pass http://frontend_upstream;
        include /etc/nginx/app/include.forwarded;
        include /etc/nginx/app/include.websocket;
        proxy_redirect off;
    }
}
